app/src/app/classes/stix/tactic.ts, docs/changelog.md
=> fixed incorrect computation of tactic shortnames

app/src/app/views/stix/group/group-list/group-list.component.html, app/src/app/views/stix/matrix/matrix-list/matrix-list.component.html, app/src/app/views/stix/mitigation/mitigation-list/mitigation-list.component.html, app/src/app/views/stix/software/software-list/software-list.component.html, app/src/app/views/stix/tactic/tactic-list/tactic-list.component.html, app/src/app/views/stix/technique/technique-list/technique-list.component.html, app/src/style/layouts/list-page.scss
PR to fix view/edit buttons by refactoring popover on STIX list page.
s.
=> Refactoring popover to enable view/edit buttons.

docs/changelog.md
=> Update the change log to include more REST API issues

app/src/app/util/cookies.ts
=> Added SameSite=Strict to deleteCookie() helper function

app/src/app/services/connectors/rest-api/rest-api-connector.service.ts, app/src/app/views/admin-page/admin-page.component.ts, app/src/app/views/admin-page/user-accounts-page/user-accounts-page.component.html, app/src/app/views/admin-page/user-accounts-page/user-accounts-page.component.ts, app/src/app/views/landing-page/landing-page.component.ts
Left out functionality to paginate user accounts table--users can now view all user accounts if there are more than 10 accounts or more than 1 page of accounts
=> Added usability to applyControls() on user accounts table pagination

app/src/app/classes/stix/technique.ts, app/src/app/views/stix/technique/technique-view/technique-view.component.html
Adding `Requires Network?` to Exfiltration techniques.
Updating `Remote Support?` to `Supports Remote?` to be consistent with the ATT&CK website.
=> Adding requires remote and updating supports remote

app/src/app/app.component.ts, app/src/app/components/resources-drawer/resources-drawer.component.html, app/src/app/components/resources-drawer/resources-drawer.component.ts, app/src/app/services/connectors/authentication/authentication.service.ts, app/src/app/views/landing-page/landing-page.component.ts
Fixes the two unexpected API requests that are triggered before a user logs in. Resolves #314
=> Fix unexpected api calls

app/src/app/classes/stix/stix-object.ts
=> Fix deserialization of ATT&CK IDs

app/src/app/services/connectors/rest-api/rest-api-connector.service.ts
=> Encode search params

app/src/app/classes/stix/stix-object.ts, app/src/app/classes/stix/technique.ts, app/src/app/components/stix/list-property/list-edit/list-edit.component.html, app/src/app/components/stix/list-property/list-edit/list-edit.component.scss, app/src/app/components/stix/list-property/list-edit/list-edit.component.ts, app/src/app/views/stix/technique/technique-view/technique-view.component.html
=> Validate that techniques have at least one tactic

docs/integrations.md
Updates the integration documentation to match the changes to the Navigator configuration file in [#370](https://github.com/mitre-attack/attack-navigator/issues/370)
=> update integration docs

app/src/app/components/reference-edit-dialog/reference-edit-dialog.component.html
=> check length of relationship patches

app/src/app/app-routing-stix.module.ts, app/src/app/components/delete-dialog/delete-dialog.component.html, app/src/app/components/delete-dialog/delete-dialog.component.ts, app/src/app/services/editor/editor.service.ts, app/src/app/views/stix/data-component/data-component-view/data-component-view.component.html, app/src/app/views/stix/data-source/data-source-view/data-source-view.component.ts, app/src/app/views/stix/stix-dialog/stix-dialog.component.html, app/src/app/views/stix/stix-dialog/stix-dialog.component.ts
- Added capability to delete data source objects that do not have any data components
- Added capability to delete data component objects that do not have any relationships with techniques
Resolves #346 and #347
=> Delete data source and data component objects

app/package-lock.json, app/package.json, app/src/app/components/stix/ordered-list-property/ordered-list-property.component.ts, app/src/app/components/stix/ordered-list-property/ordered-list-view/ordered-list-view.component.html, app/src/app/components/stix/ordered-list-property/ordered-list-view/ordered-list-view.component.ts, app/src/app/views/stix/matrix/matrix-view/matrix-view.component.html, docs/changelog.md
=> add links to tactic pages on matrix view page

app/src/app/services/connectors/rest-api/rest-api-connector.service.ts, app/src/app/views/stix/tactic/tactic-view/tactic-view.component.html, app/src/app/views/stix/tactic/tactic-view/tactic-view.component.ts, docs/changelog.md
=> 390 view associated techniques

app/src/app/components/stix/stix-list/stix-list.component.ts, app/src/app/services/connectors/rest-api/rest-api-connector.service.ts, app/src/app/views/stix/tactic/tactic-view/tactic-view.component.ts, docs/changelog.md, docs/usage.md
=> Ability to filter by platform or domain

docker-compose-resources/nginx/nginx.conf, docs/changelog.md
=> 387 increase request timeout

app/src/app/services/connectors/rest-api/rest-api-connector.service.ts, app/src/app/views/stix/collection/collection-view/collection-view.component.html, app/src/app/views/stix/collection/collection-view/collection-view.component.scss, app/src/app/views/stix/collection/collection-view/collection-view.component.ts
=> Add option to include associated notes in bundle export

app/package-lock.json, app/package.json, app/src/app/classes/stix/stix-object.ts, app/src/app/components/resources-drawer/reference-manager/reference-edit-dialog/reference-edit-dialog.component.html, docs/changelog.md
=> Bug fixes for #356 and #422

app/src/app/components/toolbar/toolbar.component.html, app/src/app/components/toolbar/toolbar.component.scss, app/src/app/views/stix/stix-dialog/stix-dialog.component.html, app/src/app/views/stix/stix-dialog/stix-dialog.component.scss
=> Add tooltip to disabled delete button

app/src/app/classes/stix/data-component.ts, app/src/app/classes/stix/data-source.ts, app/src/app/components/stix/list-property/README.md, app/src/app/components/stix/list-property/list-edit/list-edit.component.html, app/src/app/components/stix/list-property/list-edit/list-edit.component.ts, app/src/app/components/stix/stix-list/stix-list.component.ts, app/src/app/views/stix/data-component/data-component-view/data-component-view.component.html, app/src/app/views/stix/data-source/data-source-view/data-source-view.component.html, app/src/app/views/stix/data-source/data-source-view/data-source-view.component.ts, docs/changelog.md
=> Support for Mobile/ICS Data Sources

app/src/app/views/stix/campaign/campaign-list/campaign-list.component.html, app/src/app/views/stix/data-source/data-source-list/data-source-list.component.html, app/src/app/views/stix/group/group-list/group-list.component.html, app/src/app/views/stix/matrix/matrix-list/matrix-list.component.html, app/src/app/views/stix/mitigation/mitigation-list/mitigation-list.component.html, app/src/app/views/stix/software/software-list/software-list.component.html, app/src/app/views/stix/tactic/tactic-list/tactic-list.component.html, app/src/app/views/stix/technique/technique-list/technique-list.component.html
=> update popover syntax

app/src/app/components/save-dialog/save-dialog.component.ts, docs/changelog.md
Creates a `subtechnique-of` relationship when assigning an existing technique as a sub-technique.
Closes #446
=> Create subtechnique-of relationship

.github/workflows/publish.yml
Closes #486 
See REST API PR [#269](https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/pull/269) for details on how it works.
=> Refactor Docker Image Publish Workflow

app/src/app/views/stix/collection/collection-index/collection-index-view/collection-index-view.component.html, docs/changelog.md
=> 222 collection index md

app/src/app/classes/stix/data-component.ts, app/src/app/components/stix/stix-list/stix-list.component.ts, app/src/app/services/connectors/rest-api/rest-api-connector.service.ts, app/src/app/views/stix/data-source/data-source-view/data-source-view.component.html, app/src/app/views/stix/data-source/data-source-view/data-source-view.component.ts, docs/changelog.md
Displays techniques detected by data components on the data source page.
Resolves #255
=> View mapped techniques for data sources

app/package-lock.json, app/src/app/app.module.ts, app/src/app/classes/stix/stix-object.ts, app/src/app/components/reference-edit-dialog/reference-edit-dialog.component.ts, app/src/app/components/resources-drawer/reference-sidebar/reference-sidebar.component.html, app/src/app/components/resources-drawer/reference-sidebar/reference-sidebar.component.scss, app/src/app/components/resources-drawer/resources-drawer.component.html, app/src/app/components/resources-drawer/resources-drawer.component.ts, app/src/app/components/resources-drawer/search/search.component.html, app/src/app/components/resources-drawer/search/search.component.scss, app/src/app/components/resources-drawer/search/search.component.spec.ts, app/src/app/components/resources-drawer/search/search.component.ts, app/src/app/components/save-dialog/save-dialog.component.ts, app/src/app/components/stix/attackid-property/attackid-property.component.html, app/src/app/components/stix/descriptive-property/descriptive-view/descriptive-view.component.ts, app/src/app/components/toolbar/toolbar.component.ts, app/src/app/services/connectors/rest-api/rest-api-connector.service.ts, app/src/app/services/editor/editor.service.ts, app/src/app/services/sidebar/sidebar.service.ts, app/src/app/views/contributors-page/contributors-page.component.ts, app/src/app/views/reference-manager/reference-manager.component.ts, app/src/app/views/stix/collection/collection-view/collection-view.component.ts, docs/changelog.md
Added a search tab to the resources drawer. This allows users to easily search for objects by name and ID. Each result from the search includes a link to the object's Workbench page and the ability to copy its LinkByID tag.
Related to [rest-api#328](https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/pull/328)
Resolves #15
=> Search drawer

app/src/app/classes/stix/stix-object.ts, app/src/app/components/stix/descriptive-property/descriptive-view/descriptive-view.component.ts
Added validation to LinkById queries to account for cases in which more than one object is returned by the query.
=> Validate LinkByIds

app/src/app/services/website-integration/website-integration.service.ts, docs/changelog.md
=> 526 add asset support to website integration service

app/src/app/components/resources-drawer/history-timeline/history-timeline.component.html, app/src/app/components/resources-drawer/history-timeline/history-timeline.component.scss, app/src/app/components/resources-drawer/history-timeline/history-timeline.component.ts
=> View collection events in object history

app/package-lock.json, app/src/app/views/stix/collection/collection-import/collection-import-workflow/collection-import.component.html, app/src/app/views/stix/collection/collection-import/collection-import-workflow/collection-import.component.ts
- Package updates
- Resolves #610
=> Fix collection import
