- app/src/app/views/stix/group/group-list/group-list.component.html
- app/src/app/views/stix/group/group-list/group-list.component.ts
- app/src/app/views/stix/matrix/matrix-list/matrix-list.component.html
- app/src/app/views/stix/mitigation/mitigation-list/mitigation-list.component.html
- app/src/app/views/stix/software/software-list/software-list.component.html
- app/src/app/views/stix/tactic/tactic-list/tactic-list.component.html
- app/src/app/views/stix/technique/technique-list/technique-list.component.html
- app/src/style/layouts/list-page.scss
- docs/changelog.md
PR to add object documentation on object list pages.
Example:
Closes #221
> Adding object documentation on object list page

- app/package-lock.json
- app/package.json
- app/src/app/services/connectors/rest-api/rest-api-connector.service.ts
- app/src/app/views/stix/collection/collection-import/collection-import-workflow/collection-import.component.html
- app/src/app/views/stix/collection/collection-import/collection-import-workflow/collection-import.component.scss
- app/src/app/views/stix/collection/collection-import/collection-import-workflow/collection-import.component.ts
- app/src/style/layouts/expansion-panel.scss
- docs/changelog.md
- The user will now be provided with a downloadable list of objects that could not be saved (and the reason why) in the event of collection import errors.
- Frontend will now log import errors to the console when the application environment is not set to production.
- Frontend will no longer claim objects were imported when they were actually discarded due to import errors such as spec violations.
- Updated changelog for v1.0.3 release.
> Improve visibility of errors when importing collections

- app/package-lock.json
- app/package.json
- app/src/app/classes/stix/relationship.ts
- app/src/app/components/resources-drawer/reference-manager/reference-edit-dialog/reference-edit-dialog.component.ts
- app/src/app/components/stix/descriptive-property/descriptive-property.component.ts
- app/src/app/components/stix/external-references-property/external-references-view/external-references-view.component.html
- app/src/app/components/stix/external-references-property/external-references-view/external-references-view.component.ts
- app/src/app/components/stix/name-property/name-property.component.html
- app/src/app/components/stix/name-property/name-property.component.ts
- app/src/app/views/stix/relationship/relationship-view/relationship-view.component.html
- app/src/app/views/stix/relationship/relationship-view/relationship-view.component.ts
- app/src/app/views/stix/software/software-view/software-view.component.html
- app/src/app/views/stix/technique/technique-view/technique-view.component.html
- app/src/app/views/stix/technique/technique-view/technique-view.component.scss
- Fixes broken external reference links at the bottom of object pages. Resolves #306 
- Adds a link to the parent technique page from the sub-technique page. Resolves #309 
- Adds a default `retrieved` date to new references. Resolves #305 
- Rearrange fields on object pages to better follow selection order. Resolves #302 
- Show the source and target objects' versions and last modified date in the relationship dialog. Resolves #313
> v1.3.1 minor improvements

- app/src/app/components/resources-drawer/reference-manager/reference-edit-dialog/reference-edit-dialog.component.html
- app/src/app/components/resources-drawer/reference-manager/reference-edit-dialog/reference-edit-dialog.component.scss
- app/src/app/components/resources-drawer/reference-manager/reference-edit-dialog/reference-edit-dialog.component.ts
- app/src/app/components/resources-drawer/reference-manager/reference-manager.component.html
- app/src/app/components/resources-drawer/reference-manager/reference-manager.component.ts
Adds a reference view page. Summary of changes:
- After creating a new reference, the reference is shown in the view dialog, s.t. users can copy the citation without a separate search and check to ensure the reference is correct
- The option to edit a reference moved from the reference list to the reference view dialog
- Fixes a bug where an existing reference search query was no longer applied after viewing & closing a reference
Resolves #304
> Reference View

- app/src/app/classes/stix/tactic.ts
- app/src/app/classes/stix/technique.ts
- app/src/app/components/stix/list-property/list-edit/list-edit.component.html
- app/src/app/components/stix/list-property/list-edit/list-edit.component.ts
- app/src/app/views/stix/tactic/tactic-view/tactic-view.component.html
- app/src/app/views/stix/technique/technique-view/technique-view.component.html
- Adds serialization/deserialization of `x_mitre_contributors` field to Tactic and Technique objects
- Adds viewing/editing contributors on Tactic and Technique pages
- Fixes a bug in the contributors field where the input would populate with the remaining values in the list when the user removes a contributor
Resolves #325
> Add contributor field to tactics & techniques

- app/src/app/services/connectors/rest-api/rest-api-connector.service.ts
Fixes a visual bug in the snackbar that appears after successfully revoking an object, the popup appears as `[unknown object] revoked by [unknown object]`.
The bug was caused by accessing the optional `source_object` and `target_object` variables which are not defined when creating a `revoked-by` relationship object.
> Fix for revoked-by relationship pop-up

- app/src/app/components/stix/attackid-property/attackid-property.component.html
- app/src/app/components/stix/attackid-property/attackid-property.component.scss
- app/src/app/components/stix/attackid-property/attackid-property.component.ts
Adds a button to the ATT&CK ID field to copy the object's LinkById tag in the format `(LinkById: <ATT&CK ID>)`. 
Resolves #327
> copy LinkByIds

- app/src/app/components/resources-drawer/notes-editor/notes-editor.component.scss
- app/src/app/components/resources-drawer/notes-editor/notes-editor.component.ts
- app/src/app/services/connectors/rest-api/rest-api-connector.service.ts
- Fixes an error when retrieving all objects from the REST API where Note was not registered as a valid class
- Addresses some other issues with Notes:
- Fixes a css issue where a scrollbar is shown in the Notes title field for single line titles
- Reloads notes after creating a new note, which fixes an issue where new notes did not appear until the user reloaded the page
> added Note to 'stixTypeToClass'

- app/src/app/views/help-page/help-page.component.ts
- docs/changelog.md
- Updates the changelog for versions 1.3.0, 1.3.1, and 1.3.2
- Fixes the anchors for headers that begin with a digit (e.g. level 2 headers in the changelog that begin with dates `23 April 2022`), since the `querySelector` function does not support selectors that begin with digits.
> Docs/update changelog 1.3.2

- .github/workflows/publish.yml
Adding github workflow to automatically build and publish docker image on `develop` and `master`
> create github action to build and publish docker image

- app/src/app/app-routing-stix.module.ts
- app/src/app/classes/stix/collection.ts
- app/src/app/classes/stix/data-component.ts
- app/src/app/classes/stix/data-source.ts
- app/src/app/classes/stix/group.ts
- app/src/app/classes/stix/identity.ts
- app/src/app/classes/stix/marking-definition.ts
- app/src/app/classes/stix/matrix.ts
- app/src/app/classes/stix/mitigation.ts
- app/src/app/classes/stix/note.ts
- app/src/app/classes/stix/relationship.ts
- app/src/app/classes/stix/software.ts
- app/src/app/classes/stix/stix-object.ts
- app/src/app/classes/stix/tactic.ts
- app/src/app/classes/stix/technique.ts
- app/src/app/components/toolbar/toolbar.component.html
- app/src/app/components/toolbar/toolbar.component.ts
- app/src/app/services/editor/editor.service.ts
- app/src/app/views/stix/stix-page/stix-page.component.ts
- Added a delete control to stix object toolbar, which is disabled if the objects have existing relationships or if the object has not yet been saved to the database
- Added deletion capabilities for Mitigation, Software and Group objects. All related notes are also deleted and the user is navigated back to the object's respective list page.
Resolves #342
> Delete Mitigations, Software, and Groups

- app/src/app/components/reference-edit-dialog/reference-edit-dialog.component.html
- app/src/app/services/connectors/rest-api/rest-api-connector.service.ts
- app/src/app/views/reference-manager/reference-manager.component.ts
- Fixes a bug preventing users from creating a new reference (this bug was introduced by a previous v1.3.0 feature)
- Fixes a bug caused by special characters in a reference source name, where the source name url was not being encoded before pinging the REST API
> Reference validation update

- docs/integrations.md
- Adds the authentication configuration to the example version object
- Removes an outdated note that was fixed in [navigator#370](https://github.com/mitre-attack/attack-navigator/issues/370)
> update integration docs for nav compatibility with Workbench v1.2.0

- app/src/app/classes/stix/stix-object.ts
- app/src/app/components/stix/descriptive-property/descriptive-view/descriptive-view.component.ts
- app/src/app/services/connectors/rest-api/rest-api-connector.service.ts
Update REST API Service retrieve all endpoint to support searching on multiple ATT&CK IDs. Related to [rest-api#225](https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/issues/225).
> Optimize LinkByIds

- app/src/app/app.component.ts
- app/src/app/globals.ts
- app/tslint.json
- Closes #242 
- When the user initially opens Workbench, the theme will be set based on the user's OS/browser settings, rather than always setting it to light mode. 
- Details in Issue comment [here](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/242#issuecomment-1363981583).
- Added TSLint rule `{ "whitespace": { "options": [ "check-module ] }` to enforce spaces between curly brackets in the import statements.
- _e.g._, Before: 
```
import {Theme} from './globals';
```
After:
```
import { Theme } from './globals';
```
> 242 sync color theme with os settings

- app/src/app/app.component.ts
Sets the theme class on the overlay container element when using the system/browser default for light/dark mode.
Also ignores changes to the system/browser default after the user clicks the 'toggle theme' button.
closes #436
> Fix bug with setting light/dark mode from system/browser default

- README.md
- docs/usage.md
Documentation for collection import, matrix view, and default landing page
> add documentation for default landing page and collection import

- app/src/app/components/stix/datepicker-property/datepicker-property.component.ts
- docs/changelog.md
Parses dates in UTC rather than local mode to display the same output for all timezones.
> Fix first seen/last seen date parsing

- app/src/app/classes/stix/technique.ts
- app/src/app/components/save-dialog/save-dialog.component.html
- app/src/app/components/save-dialog/save-dialog.component.scss
- app/src/app/components/save-dialog/save-dialog.component.ts
- app/src/app/components/stix/list-property/list-edit/list-edit.component.html
- app/src/app/components/stix/list-property/list-edit/list-edit.component.scss
- app/src/app/components/stix/list-property/list-edit/list-edit.component.ts
- app/src/app/components/validation-results/validation-results.component.html
- app/src/app/components/validation-results/validation-results.component.ts
- app/src/app/views/stix/stix-page/stix-page.component.ts
- app/src/app/views/stix/technique/technique-view/technique-view.component.html
- app/src/style/layouts/labelled-box.scss
- docs/changelog.md
Implements automatic synchronization of tactics between parent techniques and their associated sub-techniques:
- When a sub-technique is saved, its tactics will be synced with its parent.
- When a parent technique is saved with updated tactics, the tactics of linked sub-techniques will be updated.
This ensures data consistency and reduces manual effort, minimizing the risk of discrepancies between related techniques. Additionally, validation prompts have been added to the save dialog to inform users that this synchronization will occur.
Resolves #171 and #233
> Automatic synchronization of tactics between parent and sub-techniques

- app/src/app/components/stix/list-property/list-edit/list-edit.component.ts
Fixed a bug that allowed users to assign a technique as a sub-technique of itself.
Closes https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/586
> Sub-technique can be Assigned as Its Own Parent

- src/app/classes/authn/role.ts
- src/app/components/users-list/users-list.component.html
- src/app/components/users-list/users-list.component.ts
This PR includes the following changes:
1. Updates TEAM_LEAD enum to team_lead to match the REST API
2. Helper function to format team_lead to 'team lead' in dropdown
To test:
1. Navigate to admin -> User Accounts
2. Click on the "role" dropdown. It should display "team lead"
Related to https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/pull/407
> Team Lead Updates

- src/app/components/users-list/users-list.component.html
Applies formatting to display 'team lead' instead of 'team_lead' in `/dashboard/user-accounts` options dropdown.
> Team Lead Formatting in User Accounts Options Dropdown

- src/app/components/stix/object-ref-property/object-ref-edit/object-ref-edit.component.ts
Fixes an issue where the Log Source IDs were not being properly displayed when adding references to an Analytic object
> fix: use configurable reference field for mapping object references

- src/app/classes/stix/analytic.ts
- src/app/classes/stix/asset.ts
- src/app/classes/stix/campaign.ts
- src/app/classes/stix/collection.ts
- src/app/classes/stix/data-component.ts
- src/app/classes/stix/data-source.ts
- src/app/classes/stix/detection-strategy.ts
- src/app/classes/stix/group.ts
- src/app/classes/stix/identity.ts
- src/app/classes/stix/marking-definition.ts
- src/app/classes/stix/matrix.ts
- src/app/classes/stix/mitigation.ts
- src/app/classes/stix/note.ts
- src/app/classes/stix/relationship.ts
- src/app/classes/stix/software.ts
- src/app/classes/stix/stix-object.ts
- src/app/classes/stix/tactic.ts
- src/app/classes/stix/technique.ts
- src/app/components/stix/attackid-property/attackid-edit/attackid-edit.component.html
- src/app/components/stix/attackid-property/attackid-edit/attackid-edit.component.ts
- src/app/views/stix/analytic-view/analytic-view.component.ts
Summary of Changes:
- `generateAttackID()` fetches the organization namespace internally, removing the need to pass it in from callers
- Centralizes prefix handling: IDs are formatted consistently and callers no longer need to handle formatting separately
- Removes redundant `supportsNamespace` boolean from all SDOs
- Simplifies and improves calculation logic for the next available ATT&CK ID
- Improve general readability and maintainability
> Refactor ATT&CK ID generator
